openapi: 3.1.0
info:
  title: ServerLab AFFiNE API
  version: 0.1.0
  description: REST façade for interacting with AFFiNE workspaces via the ServerLab toolkit.
servers:
  - url: http://localhost:3000
    description: Local runtime
paths:
  /healthz:
    get:
      summary: Health check
      operationId: getHealthz
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /workspaces/{workspaceId}/documents:
    get:
      summary: List documents in a workspace
      operationId: listDocuments
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      responses:
        '200':
          description: Collection of documents
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocumentSummary'
    post:
      summary: Create a document
      operationId: createDocument
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
      responses:
        '201':
          description: Document created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentSummary'
  /workspaces/{workspaceId}/documents/{docId}:
    get:
      summary: Retrieve a document snapshot
      operationId: getDocument
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '200':
          description: Document snapshot encoded as base64 Yjs update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentSnapshot'
        '404':
          description: Document not found
    patch:
      summary: Update a document
      operationId: updateDocument
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - $ref: '#/components/parameters/DocumentId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
      responses:
        '200':
          description: Updated document metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentSummary'
        '404':
          description: Document not found
    delete:
      summary: Delete a document
      operationId: deleteDocument
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '204':
          description: Document deleted
  /workspaces/{workspaceId}/blobs:
    get:
      summary: List all blobs in workspace
      operationId: listBlobs
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      responses:
        '200':
          description: List of blobs
          content:
            application/json:
              schema:
                type: object
                properties:
                  blobs:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                          description: Blob identifier
                        mime:
                          type: string
                          description: MIME type
                        size:
                          type: integer
                          description: Size in bytes
                        createdAt:
                          type: string
                          description: Unix timestamp (milliseconds)
                  workspaceId:
                    type: string
    post:
      summary: Upload a file to blob storage
      operationId: uploadBlob
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fileName
                - content
              properties:
                fileName:
                  type: string
                  description: Name of the file
                content:
                  type: string
                  description: Base64-encoded file content (data URI supported)
                mimeType:
                  type: string
                  description: MIME type of the file
      responses:
        '201':
          description: Blob uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  blobId:
                    type: string
                  workspaceId:
                    type: string
        '413':
          description: File too large (max 10MB)
  /workspaces/{workspaceId}/blobs/{blobKey}:
    get:
      summary: Download a blob
      operationId: getBlob
      description: Download blob content. Returns binary by default, or JSON with base64 content if format=base64
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - name: blobKey
          in: path
          required: true
          schema:
            type: string
          description: Blob key/identifier
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [base64]
          description: Set to 'base64' to receive JSON with base64-encoded content
      responses:
        '200':
          description: Blob content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Base64-encoded blob content
                  mime:
                    type: string
                  size:
                    type: integer
                  key:
                    type: string
        '404':
          description: Blob not found
  /workspaces/{workspaceId}/documents/{docId}/images:
    post:
      summary: Upload image and create image block
      operationId: addImageBlock
      description: Uploads an image to blob storage and creates an affine:image block in the document
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - $ref: '#/components/parameters/DocumentId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - parentBlockId
                - fileName
                - content
              properties:
                parentBlockId:
                  type: string
                  description: ID of the parent block (usually affine:note)
                fileName:
                  type: string
                  description: Name of the image file
                content:
                  type: string
                  description: Base64-encoded image content
                mimeType:
                  type: string
                  description: MIME type (e.g., image/png)
                caption:
                  type: string
                  description: Optional image caption
                width:
                  type: integer
                  description: Optional width in pixels
                height:
                  type: integer
                  description: Optional height in pixels
                position:
                  oneOf:
                    - type: string
                      enum: [start, end]
                    - type: integer
                  description: Position among siblings
      responses:
        '201':
          description: Image block created
          content:
            application/json:
              schema:
                type: object
                properties:
                  blockId:
                    type: string
                  blobId:
                    type: string
                  workspaceId:
                    type: string
                  docId:
                    type: string
        '413':
          description: File too large (max 10MB)
components:
  parameters:
    WorkspaceId:
      name: workspaceId
      in: path
      required: true
      schema:
        type: string
      description: AFFiNE workspace identifier
    DocumentId:
      name: docId
      in: path
      required: true
      schema:
        type: string
      description: AFFiNE document identifier
  schemas:
    DocumentSummary:
      type: object
      properties:
        docId:
          type: string
        title:
          type: string
          nullable: true
        createDate:
          type: integer
          format: int64
          nullable: true
        updatedDate:
          type: integer
          format: int64
          nullable: true
        tags:
          type: array
          items:
            type: string
        folderId:
          type: string
          nullable: true
        folderNodeId:
          type: string
          nullable: true
      required:
        - docId
        - tags
    DocumentSnapshot:
      allOf:
        - $ref: '#/components/schemas/DocumentSummary'
        - type: object
          properties:
            update:
              type: string
              description: Base64-encoded Yjs update representing the document state
    DocumentRequest:
      type: object
      properties:
        docId:
          type: string
        title:
          type: string
        content:
          type: string
        markdown:
          type: string
        folderId:
          type: string
          nullable: true
        folderNodeId:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: string
      additionalProperties: false
